### ISSUE TITLE
AREPL hangs on generator initialization

### ISSUE THREAD

**Issue by purpledot** [Almenon/AREPL-backend#96]
Ubuntu 18.04.2 LTS; Python 3.7.1, 3.7.4; vscode 1.38.0; AREPL 1.0.17

Case 1:
```python
def count(start=0):
    while True:
        yield start
        start += 1

counter = count()
```
Case 2:
```python
import itertools

counter = (x for x in itertools.count())
```

**Comment by Almenon** [comment]
I added a print statement in line 230:

```python
    def _max_reached(self):
        # i printed depth and max depth
        return self._depth == self._max_depth
```

> 0-100
1-100
2-100
2-100
2-100
etc...

As you can see for some reason the depth never gets above two so the _max_depth limit that is supposed to prevent infinite execution is never reached.

**Comment by Almenon** [comment]
It turns out this isn't a bug with jsonpickle - you can pass in a option max_iter to control how many iterations of data arepl pickles when going through a object.
Unfortunately, limiting this value would cause another bug - large arrays would appear to have less values than they actually have.

I fixed it by adding a custom handler for generators - fix should come out soon, probably by sometime next week at latest.

**Comment by Almenon** [comment]
Closing the issue for this repo - I'll ping you once the new version of the extension is released. Thanks for reporting this!

**Comment by Almenon** [comment]
oh hey i didn't know semantic release bot commented. That's pretty cool!

**Comment by Almenon** [comment]
@purpledot I just released a new version of the extension - once you update to 1.0.18 the issue should be fixed :)
